### ISSUE TITLE
Add a client generator.

### ISSUE THREAD

**Issue by bddap** [layer1capital/easy-jsonrpc#3]
A client generator will likely generate a concrete type that borrows some sort of duplex io stream.

## Possible implementaion 1

Macro Input:

```rust
#[easy_jsonrpc::jsonrpc_client]
trait Adder {
    fn checked_add(&self, a: usize, b: usize) -> Option<usize>;
}
```

Output

```rust
// ...

struct<'a, S: io::Stream> AdderClient<'a, S> {
    stream: &'a mut S,
}

impl <'a, S: io::Stream> AdderClient<'a, S> {
    fn checked_add(&self, a: usize, b: usize)
        -> Future<Item = Result<Option<usize>, serde::de::Error>, Error = S::Error> {
        // ...
    }
}
```

PROS:
- Ergonomic, plug in tcp socket and start making requests.
CONS:
- Does not expose intermediate steps
- Requires std::io::Stream or whatever
- Adds new macro, easy_jsonrpc::jsonrpc_client, which may not be needed

**Comment by bddap** [comment]
## Possible implementaion 2

Macro Input:

```rust
#[easy_jsonrpc::jsonrpc]
trait Adder {
    fn checked_add(&self, a: usize, b: usize) -> Option<usize>;
}
```

Output

```rust
// original trait definition ...

// server impl ...

// client impl ...
```

PROS:
- only one macro needs to be exposed

CONS:
- doesn't specify client implementation

**Comment by bddap** [comment]
## Possible implementaion 3

Macro Input:

```rust
#[easy_jsonrpc::jsonrpc_client]
trait Adder {
    fn checked_add(&self, a: usize, b: usize) -> Option<usize>;
}
```

Output

```rust
// ...

mod adder_client {
    struct checked_add { id: usize };
    impl checked_add {
        fn call(a: usize, b: usize) -> (MethodCall, Self) { .. }  // calls with random id
        fn notification(a: usize, b: usize) -> Notification { .. } 
        fn response(&self, response: &Output)
            -> Result<Option<usize>, easy_jsonrpc::ResponseFail> { .. } // parses response
    }
}
```

Elsewhere, define ResponseParseFailure:

```rust
enum ResponseFail {
    IdMismatch,
    InvalidResponse, // returned on serde::de failure
}
```

PROS:

- Exposes intermediate values
- Does not need to know about io::Stream or whatever
- Functions are likely composable into a future.
- Id checking is enforced with types
- Feels right

CONS:

- Adds new macro, easy_jsonrpc::jsonrpc_client, which may not be needed

**Comment by casey** [comment]
Is Grin using Futures? You might want to check with Igno. I think Grin used to be async using combinators, but they were too much of a mess, so they switched to threads + blocking io.

**Comment by bddap** [comment]
The current api involves no futures, it's all blocking. Anything specific you think I should ask Igno?

**Comment by casey** [comment]
Sorry for the delay, I've been letting my mail pile up. Ah, gotcha. Nope, nothing else specific to ask Igno.

**Comment by bddap** [comment]
Done, as of 327fae5015f9e0c44413882654d0ff1db3859daf.

Went with implementation 3, except functions are represented as modules instead of new structs.
`struct checked_add` -> `mod checked_add`.
